title Windows DeadSystem 1.0 Setup
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
msg * sdjfsdhfsdjb
msg * dhfdsfhsdfdsfsj
msg * dskfsdshdfjksdhfdksj
 